name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package:
    name: package hashicorp/vscode-terraform
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install g++ libx11-dev libxkbfile-dev libsecret-1-dev
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/checkout@v2
      with:
        repository: hashicorp/vscode-terraform
        ref: v2.1.1
    - run: npm install
    - run: npx vsce package
